# Bella — developer entrypoints.
#
# Everything runs in Docker. There is no requirement to have Python, Node, pnpm or uv
# installed on the host; `make bootstrap` on a clean machine with Docker gets you a
# running stack.

SHELL := /bin/bash
.DEFAULT_GOAL := help
.PHONY: help bootstrap build up down restart logs ps clean nuke \
        migrate migrate-auto migrate-down migrate-history migrate-test \
        shell-api shell-web shell-db redis-cli \
        lint format typecheck test test-api test-web test-e2e check \
        prod-build prod-up openapi

# Tooling containers write into the bind mount (ruff --fix, autogenerated migrations),
# so they run as the invoking user rather than the image's uid. Exported for compose.
export DOCKER_UID := $(shell id -u)
export DOCKER_GID := $(shell id -g)

COMPOSE := docker compose
COMPOSE_PROD := docker compose -f compose.yaml -f compose.prod.yaml
RUN_API := $(COMPOSE) run --rm --no-deps --user $(DOCKER_UID):$(DOCKER_GID) api
EXEC_API := $(COMPOSE) exec api
EXEC_WEB := $(COMPOSE) exec web

# ── help ──────────────────────────────────────────────────────────────────────
help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# ── lifecycle ─────────────────────────────────────────────────────────────────
bootstrap: ## First-run setup: env file, build images, start, migrate
	@test -f .env || (cp .env.example .env && echo "→ created .env from .env.example")
	$(COMPOSE) build
	$(COMPOSE) up -d
	@echo "→ waiting for postgres…"
	@until $(COMPOSE) exec -T postgres pg_isready -U bella -d bella >/dev/null 2>&1; \
		do sleep 1; done
	$(MAKE) migrate
	@echo ""
	@echo "  web      http://localhost:3000"
	@echo "  api      http://localhost:8000/docs"
	@echo "  mail     http://localhost:8025"
	@echo ""

build: ## Build all images
	$(COMPOSE) build

up: ## Start the stack
	$(COMPOSE) up -d

down: ## Stop the stack (volumes preserved)
	$(COMPOSE) down --remove-orphans

restart: ## Restart application services
	$(COMPOSE) restart api worker web

logs: ## Follow logs (make logs SERVICE=api)
	$(COMPOSE) logs -f $(SERVICE)

ps: ## Show service status
	$(COMPOSE) ps

clean: ## Stop and remove containers and networks
	$(COMPOSE) down --remove-orphans

nuke: ## Stop everything and DELETE ALL LOCAL DATA
	@read -p "This deletes the local database and all volumes. Type 'yes': " ok; \
		[ "$$ok" = "yes" ] || (echo "aborted"; exit 1)
	$(COMPOSE) down -v --remove-orphans

# ── database ──────────────────────────────────────────────────────────────────
migrate: ## Apply migrations
	$(COMPOSE) run --rm migrate

migrate-auto: ## Autogenerate a migration (make migrate-auto M="add widgets")
	@test -n "$(M)" || (echo "usage: make migrate-auto M=\"description\""; exit 1)
	$(COMPOSE) run --rm migrate alembic revision --autogenerate -m "$(M)"

migrate-down: ## Roll back one migration
	$(COMPOSE) run --rm migrate alembic downgrade -1

migrate-history: ## Show migration history
	$(COMPOSE) run --rm migrate alembic history --indicate-current

# ── shells ────────────────────────────────────────────────────────────────────
shell-api: ## Shell into the API container
	$(EXEC_API) bash

shell-web: ## Shell into the web container
	$(EXEC_WEB) sh

shell-db: ## psql into the development database
	$(COMPOSE) exec postgres psql -U bella -d bella

redis-cli: ## redis-cli into the cache
	$(COMPOSE) exec redis redis-cli

# ── quality ───────────────────────────────────────────────────────────────────
lint: ## Lint everything
	$(RUN_API) ruff check app tests
	$(RUN_API) ruff format --check app tests
	$(EXEC_WEB) pnpm lint

format: ## Auto-format everything
	$(RUN_API) ruff check --fix app tests
	$(RUN_API) ruff format app tests
	$(EXEC_WEB) pnpm format

typecheck: ## Type-check everything
	$(RUN_API) mypy app
	$(EXEC_WEB) pnpm typecheck

test: test-api test-web ## Run all unit and integration tests

migrate-test: ## Bring the test database up to head (as the migrator role)
	$(COMPOSE) run --rm \
		-e DATABASE_URL=postgresql://bella_migrator:bella_migrator_local@postgres:5432/bella_test \
		migrate alembic upgrade head

test-api: migrate-test ## Run the API suite against the isolated test database
	@# Connects as the RUNTIME role so Row-Level Security is actually exercised —
	@# running the suite as the owner would make every isolation test pass vacuously.
	$(COMPOSE) run --rm \
		-e DATABASE_URL=postgresql://bella_app:bella_app_local@postgres:5432/bella_test \
		-e TEST_ADMIN_DATABASE_URL=postgresql+asyncpg://bella_migrator:bella_migrator_local@postgres:5432/bella_test \
		-e ENVIRONMENT=test \
		--user $(DOCKER_UID):$(DOCKER_GID) \
		api pytest --cov=app --cov-report=term-missing

test-web: ## Run the web unit suite
	$(EXEC_WEB) pnpm test

test-e2e: ## Run Playwright end-to-end tests
	$(EXEC_WEB) pnpm test:e2e

check: lint typecheck test ## Everything CI runs

# ── artefacts ─────────────────────────────────────────────────────────────────
openapi: ## Write the OpenAPI schema to packages/api-client/openapi.json
	@mkdir -p packages/api-client
	$(RUN_API) python -c "import json; from app.main import create_app; \
		print(json.dumps(create_app().openapi(), indent=2))" > packages/api-client/openapi.json
	@echo "→ packages/api-client/openapi.json"

# ── production images ─────────────────────────────────────────────────────────
prod-build: ## Build the production image targets
	$(COMPOSE_PROD) build

prod-up: ## Boot the production images locally to verify they start
	$(COMPOSE_PROD) up -d
