"""core schema

Revision ID: 8044448e27c7
Revises: a1b2c3d4e5f6
Created: 2026-08-09 06:23:20.305853

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8044448e27c7"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_role", sa.String(length=16), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_action",
        "audit_log",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_actor",
        "audit_log",
        ["actor_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_target_user",
        "audit_log",
        ["target_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rollout_pct", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "user_allowlist",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rollout_pct BETWEEN 0 AND 100", name=op.f("ck_feature_flags_rollout_pct_range")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_feature_flags")),
    )
    op.create_table(
        "users",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("display_id", sa.String(length=16), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'member'"), nullable=False),
        sa.Column("is_minor", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("guardian_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "locale", sa.String(length=16), server_default=sa.text("'en-IN'"), nullable=False
        ),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default=sa.text("'Asia/Kolkata'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('member', 'admin', 'owner')", name=op.f("ck_users_role_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deletion_requested', 'deleted')",
            name=op.f("ck_users_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["guardian_user_id"],
            ["users.id"],
            name=op.f("fk_users_guardian_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("display_id", name=op.f("uq_users_display_id")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("firebase_uid", name=op.f("uq_users_firebase_uid")),
        sa.UniqueConstraint("phone_e164", name=op.f("uq_users_phone_e164")),
    )
    op.create_index(
        "ix_users_status",
        "users",
        ["status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "consents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("granted_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('terms', 'privacy', 'memory_storage', 'voice_recording', 'location', 'analytics', 'marketing')",
            name=op.f("ck_consents_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_consents_granted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_consents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(
        "ix_consents_user_kind",
        "consents",
        ["user_id", "kind", sa.literal_column("granted_at DESC")],
        unique=False,
    )
    op.create_table(
        "data_requests",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("artifact_key", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('export', 'deletion', 'rectification')",
            name=op.f("ck_data_requests_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'rejected', 'cancelled')",
            name=op.f("ck_data_requests_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_data_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_requests")),
    )
    op.create_index(
        "ix_data_requests_open",
        "data_requests",
        ["status", "due_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("pronunciation", sa.String(length=200), nullable=True),
        sa.Column("pronouns", sa.String(length=50), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("avatar_object", sa.String(length=512), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("group_name", sa.String(length=100), nullable=True),
        sa.Column(
            "tone_preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("cohort", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_prompt_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_prompt_versions_name_version"),
    )
    op.create_index(
        "ix_prompt_versions_active",
        "prompt_versions",
        ["name", "cohort"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "relationships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("related_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ask_about", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "sensitivity", sa.String(length=16), server_default=sa.text("'normal'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "sensitivity IN ('normal', 'high')", name=op.f("ck_relationships_sensitivity_valid")
        ),
        sa.ForeignKeyConstraint(
            ["related_user_id"],
            ["users.id"],
            name=op.f("fk_relationships_related_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_relationships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
    )
    op.create_index(
        "ix_relationships_user_ask",
        "relationships",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("ask_about"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.String(length=200), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index("ix_sessions_family", "sessions", ["family_id"], unique=False)
    op.create_index("ix_sessions_token_hash", "sessions", ["refresh_token_hash"], unique=True)
    op.create_index(
        "ix_sessions_user_active",
        "sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "threads",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "title",
            sa.String(length=200),
            server_default=sa.text("'New Conversation'"),
            nullable=False,
        ),
        sa.Column("title_generated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_upto_seq", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_threads_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threads")),
    )
    op.create_index(
        "ix_threads_user_recent",
        "threads",
        ["user_id", sa.literal_column("last_message_at DESC")],
        unique=False,
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "user_quotas",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("memories_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("memories_limit", sa.Integer(), server_default=sa.text("1000"), nullable=False),
        sa.Column("threads_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("threads_limit", sa.Integer(), server_default=sa.text("500"), nullable=False),
        sa.Column("storage_bytes_used", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "storage_limit_bytes",
            sa.Integer(),
            server_default=sa.text("2147483648"),
            nullable=False,
        ),
        sa.Column("tokens_used_today", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "tokens_limit_daily", sa.Integer(), server_default=sa.text("1000000"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_quotas_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_quotas")),
    )
    op.create_table(
        "files",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'uploading'"), nullable=False
        ),
        sa.Column("scan_result", sa.String(length=100), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extracted_chars", sa.Integer(), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('document', 'image', 'audio', 'video', 'recording')",
            name=op.f("ck_files_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('uploading', 'scanning', 'extracting', 'ready', 'failed', 'quarantined')",
            name=op.f("ck_files_status_valid"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_files_size_positive")),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
            name=op.f("fk_files_thread_id_threads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_files_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
    )
    op.create_index(
        "ix_files_expiry",
        "files",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_files_user_created",
        "files",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_files_user_sha256",
        "files",
        ["user_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("status = 'ready'"),
    )
    op.create_table(
        "messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', content)", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'complete'"), nullable=False
        ),
        sa.Column("client_message_id", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_micros", sa.BigInteger(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("first_token_ms", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system', 'tool')", name=op.f("ck_messages_role_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'streaming', 'complete', 'failed', 'cancelled')",
            name=op.f("ck_messages_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_messages_prompt_version_id_prompt_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
            name=op.f("fk_messages_thread_id_threads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("thread_id", "seq", name="uq_messages_thread_id_seq"),
        sa.UniqueConstraint(
            "user_id", "client_message_id", name="uq_messages_user_id_client_message_id"
        ),
    )
    op.create_index(
        "ix_messages_content_tsv", "messages", ["content_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_messages_thread_seq", "messages", ["thread_id", "seq"], unique=False)
    op.create_index(
        "ix_messages_user_created",
        "messages",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "file_chunks",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', content)", persisted=True),
            nullable=True,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("page_from", sa.Integer(), nullable=True),
        sa.Column("page_to", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_file_chunks_file_id_files"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_file_chunks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_chunks")),
        sa.UniqueConstraint("file_id", "chunk_index", name="uq_file_chunks_file_id_chunk_index"),
    )
    op.create_index(
        "ix_file_chunks_content_tsv",
        "file_chunks",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_file_chunks_embedding_hnsw",
        "file_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("ix_file_chunks_user", "file_chunks", ["user_id"], unique=False)
    op.create_table(
        "memories",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', content)", persisted=True),
            nullable=True,
        ),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_message_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column("salience", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column(
            "sensitivity", sa.String(length=16), server_default=sa.text("'normal'"), nullable=False
        ),
        sa.Column("pinned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("times_referenced", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_referenced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('fact', 'preference', 'pronunciation', 'followup', 'event')",
            name=op.f("ck_memories_kind_valid"),
        ),
        sa.CheckConstraint(
            "sensitivity IN ('normal', 'high')", name=op.f("ck_memories_sensitivity_valid")
        ),
        sa.CheckConstraint(
            "source IN ('user_explicit', 'extracted', 'imported', 'admin')",
            name=op.f("ck_memories_source_valid"),
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_memories_confidence_range")),
        sa.CheckConstraint("salience BETWEEN 0 AND 1", name=op.f("ck_memories_salience_range")),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
            name=op.f("fk_memories_source_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["memories.id"],
            name=op.f("fk_memories_superseded_by_memories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(
        "ix_memories_content_tsv", "memories", ["content_tsv"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_memories_embedding_hnsw",
        "memories",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("deleted_at IS NULL AND superseded_by IS NULL"),
    )
    op.create_index(
        "ix_memories_expiry",
        "memories",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("expires_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_memories_user_kind",
        "memories",
        ["user_id", "kind"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "message_attachments",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_message_attachments_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_attachments_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", "file_id", name=op.f("pk_message_attachments")),
    )
    op.create_table(
        "message_audio",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("voice_id", sa.String(length=100), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_audio_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_message_audio_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_audio")),
    )
    op.create_index("ix_message_audio_cache_key", "message_audio", ["cache_key"], unique=False)
    op.create_index("ix_message_audio_message", "message_audio", ["message_id"], unique=False)
    op.create_table(
        "tool_invocations",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_tool_invocations_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tool_invocations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_invocations")),
    )
    op.create_index("ix_tool_invocations_message", "tool_invocations", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_invocations_message", table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index("ix_message_audio_message", table_name="message_audio")
    op.drop_index("ix_message_audio_cache_key", table_name="message_audio")
    op.drop_table("message_audio")
    op.drop_table("message_attachments")
    op.drop_index(
        "ix_memories_user_kind",
        table_name="memories",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_memories_expiry",
        table_name="memories",
        postgresql_where=sa.text("expires_at IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_memories_embedding_hnsw",
        table_name="memories",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_where=sa.text("deleted_at IS NULL AND superseded_by IS NULL"),
    )
    op.drop_index("ix_memories_content_tsv", table_name="memories", postgresql_using="gin")
    op.drop_table("memories")
    op.drop_index("ix_file_chunks_user", table_name="file_chunks")
    op.drop_index(
        "ix_file_chunks_embedding_hnsw",
        table_name="file_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_file_chunks_content_tsv", table_name="file_chunks", postgresql_using="gin")
    op.drop_table("file_chunks")
    op.drop_index("ix_messages_user_created", table_name="messages")
    op.drop_index("ix_messages_thread_seq", table_name="messages")
    op.drop_index("ix_messages_content_tsv", table_name="messages", postgresql_using="gin")
    op.drop_table("messages")
    op.drop_index(
        "ix_files_user_sha256", table_name="files", postgresql_where=sa.text("status = 'ready'")
    )
    op.drop_index("ix_files_user_created", table_name="files")
    op.drop_index(
        "ix_files_expiry", table_name="files", postgresql_where=sa.text("expires_at IS NOT NULL")
    )
    op.drop_table("files")
    op.drop_table("user_quotas")
    op.drop_index(
        "ix_threads_user_recent",
        table_name="threads",
        postgresql_where=sa.text("archived_at IS NULL"),
    )
    op.drop_table("threads")
    op.drop_index(
        "ix_sessions_user_active",
        table_name="sessions",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_sessions_token_hash", table_name="sessions")
    op.drop_index("ix_sessions_family", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        "ix_relationships_user_ask",
        table_name="relationships",
        postgresql_where=sa.text("ask_about"),
    )
    op.drop_table("relationships")
    op.drop_index(
        "ix_prompt_versions_active",
        table_name="prompt_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("prompt_versions")
    op.drop_table("profiles")
    op.drop_index(
        "ix_data_requests_open",
        table_name="data_requests",
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.drop_table("data_requests")
    op.drop_index("ix_consents_user_kind", table_name="consents")
    op.drop_table("consents")
    op.drop_index(
        "ix_users_status", table_name="users", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_table("users")
    op.drop_table("feature_flags")
    op.drop_index("ix_audit_log_target_user", table_name="audit_log")
    op.drop_index("ix_audit_log_actor", table_name="audit_log")
    op.drop_index("ix_audit_log_action", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
